name: Shutdown Ephemeral Instance

inputs:
  localstack-api-key:
    description: 'LocalStack API key used to access the platform api'
    required: true
  github-token:
    description: 'Github token used to create PR comments'
    required: true
    

runs:
  using: composite
  steps:
    - name: Download PR artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
      with:
        name: pr-id

    - name: Load the PR ID
      id: pr
      shell: bash
      run: |
        safe=$(printf '%s' "$(<pr-id.txt)" | tr -d '\n\r')
        echo "pr_id=$safe" >> "$GITHUB_OUTPUT"

    - name: Setup preview name
      shell: bash
      run: |
        prId=$(<pr-id.txt)
        repoName=$GITHUB_REPOSITORY
        repoNameCleaned=$(echo -n "$repoName" | tr -c '[:alnum:]' '-')
        previewName=preview-$repoNameCleaned-$prId
        safe=$(printf '%s' "$previewName" | tr -d '\n\r')
        echo "previewName=$safe" >> $GITHUB_ENV

    - name: Shutdown ephemeral instance
      shell: bash
      env:
        INPUT_LOCALSTACK_API_KEY: ${{ inputs.localstack-api-key }}
      run: |
        apiKey="${LOCALSTACK_AUTH_TOKEN:-${LOCALSTACK_API_KEY:-${INPUT_LOCALSTACK_API_KEY}}}"
        response=$(curl -X DELETE \
            -s -o /dev/null -w "%{http_code}" \
            -H "ls-api-key: ${apiKey}" \
            -H "content-type: application/json" \
            https://api.localstack.cloud/v1/compute/instances/$previewName)
        if [[ "$response" -ne 200 ]]; then
          # In case the deletion fails, e.g. if the instance cannot be found, we raise a proper error on the platform
          echo "Unable to delete preview environment. API response: $response"
          exit 1
        fi
    
    - name: Update status comment
      uses: actions-cool/maintain-one-comment@a7467bfd0e0082d727aea4d3176c8e831e955717 # v3.1.1
      with:
        token: ${{ inputs.github-token }}
        body: |
          The ephemeral instance for the application preview has been shut down
          <!-- Sticky Pull Request Comment -->
        body-include: '<!-- Sticky Pull Request Comment -->'
        number: ${{ steps.pr.outputs.pr_id }}
